<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tnt_lightgallery"
 *
 * Auto generated by Extension Builder 2014-11-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TNT Light Gallery',
	'description' => 'TNT Light Gallery - Load Dynamically ',
	'category' => 'plugin',
	'author' => 'Abin Sabu',
	'author_email' => 'abin.s@tnt-graphics.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);